import Header from "@/components/shared/header/Header";
import "./globals.css";
import { Manrope } from "next/font/google";
import Footer from "@/components/shared/footer/Footer";

const manrope = Manrope({
  subsets: ["latin"],
  weight: "400",
});

// Santo
export const metadata = {
  title: "VortExport",
  description: "Generated by create next app",
};

interface RooteLayout {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RooteLayout) {
  return (
    // enable dark mode by default, Santo
    <html lang="en" className="dark">
      <head>
        <link rel="shortcut icon" href="/favicon.png" type="image/png" />
        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css"
          rel="stylesheet"
        />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css"
        />
      </head>
      <body className={manrope.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
