import Header from "@/components/shared/header/Header";
import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "@/components/shared/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

// Santo
export const metadata = {
  title: "VortExport",
  description: "Generated by create next app",
};

interface RooteLayout {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RooteLayout) {
  return (
    // enable dark mode by default, Santo
    <html lang="en" className="dark">
      <head>
        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css"
          rel="stylesheet"
        />
      </head>
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
